#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

# Colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Rename default index file
sudo mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

# Create new index file
echo -e "<!DOCTYPE html><html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅ \n"
