#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process using kill
# shellcheck disable=SC2009

# Get the PID of the process
pid=$(pgrep -o 4-to_infinity_and_beyond)

if [ -n "$pid" ]; then
    echo "Stopping 4-to_infinity_and_beyond (PID: $pid)"
    kill "$pid"
else
    echo "4-to_infinity_and_beyond process not found."
fi
