#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely with a sleep of 2 seconds
# shellcheck disable=SC2009

# Print "I am invincible!!!" on receiving a SIGTERM signal

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
