#!/usr/bin/env bash
# Kill the 7-highlander process when receiving a SIGTERM signal
# shellcheck disable=SC2009

trap 'kill $(pgrep -o 7-highlander) && echo "7-highlander process killed"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
