#!/usr/bin/env bash
# This script displays username, user id, and home directory path from /etc/passwd.
# shellcheck disable=SC2009

while IFS=: read -r username _ userid _ _ home_directory _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home_directory"
done < /etc/passwd

