#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data using awk.
# shellcheck disable=SC2009

awk '{count[$1" "$9]++} END {for (item in count) print count[item], item}' apache-access.log | sort -nr

