#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop
# shellcheck disable=SC2009
# Counter variable
counter=0

# Loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    echo "Best School"
    ((counter++))
done

