#!/usr/bin/env bash
# This script displays "Best School" 10 times using the until loop.
# shellcheck disable=SC2009

counter=0

until [ "$counter" -ge 10 ]; do
    echo "Best School"
    ((counter++))
done

