#!/usr/bin/env bash
# This script displays "Best School" 10 times, with a special message on the 9th iteration.
# shellcheck disable=SC2009
counter=1

while [ "$counter" -le 10 ]; do
    if [ "$counter" -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done

