#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
# shellcheck disable=SC2009
hour=0

while [ "$hour" -le 12 ]; do
    minute=1

    while [ "$minute" -le 59 ]; do
        printf "%02d:%02d\n" "$hour" "$minute"
        ((minute++))
    done

    ((hour++))
done

