#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.
# shellcheck disable=SC2009

for file in *; do
    # Check if the file is not a hidden file and is a regular file or directory
    if [[ ! "$file" =~ ^\..* && ( -f "$file" || -d "$file" ) ]]; then
        # Extract the part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)

        # Display the modified name
        echo "$name_part"
    fi
done

